### PR TITLE
Follow posts module

### LINKED ISSUE #83: Metabox for followers in the edit post screen
In the post edit screen, it'll have a screen with a list of the users following the post.

### LINKED ISSUE #84: Post deletion notification
@r-a-y I'd like your feedback here.

I'm considering what's the correct approach when an admin, editor or author is deleting a post that has users following it. What should show to the person doing the action (deleting the post) and should the user following the post be informed by email?

### PR DESCRIPTION
**Pull request by renatonascalves**
This is not ready to merge, neither should anyone to use it in a production environment.

I'm adding this PR for feedback for now. Also for those curious and interested in this feature. 
Mainly, this is going to be the base for the Post Type and Taxonomy module.

What's missing?

- [x] ~~Unit tests (on the way)~~
- [ ] Separate js to their own file
- [ ] Add support for filtering_scope 
- [ ] Add ajax instead of action_handler
- [ ] Fix #84 
- [ ] Fix #83

### CODE REVIEW

**Comment by r-a-y** [comment]
Thanks for the PR, @renatonascalves.

I think for now, you should write this as a separate plugin as I have no interest in keeping a follow posts module in BP Follow Core.

BP Follow has a hook that you can attach your code to `'bp_follow_loaded'`, which is available in v1.3-alpha.  If you need help moving your code to a separate plugin, let me know.

Also, as I mention here - https://github.com/r-a-y/buddypress-followers/issues/34#issuecomment-36555835 - you might want to consider just using a WP follow posts plugin and extending BuddyPress support for such a plugin.  Not sure why you necessarily need BP Follow for this.

**Comment by renatonascalves** [comment]
@r-a-y Thanks a lot for your feedback! =D I'm gonna create as separate plugin then. 

I'll add it here https://github.com/renatonascalves/bp-follow-post I'll let you know if I need any help with the integration. =)

About why BP Follow, I've looked at few options and didn't like them. 

BuddyPress Followers already has:

* Good integration with BuddyPress (a must for this project);
* Has a good db schema for follow types (when following post types and taxonomies);
* BuddyPress Followers will probably get into BuddyPress core in 2.8, 2.9, not so distant future.

Thanks again!

**Comment by r-a-y** [comment]
>  I'll let you know if I need any help with the integration. =)

Cool, let me know any time!

> Good integration with BuddyPress (a must for this project);

Sure, but it doesn't use an API to add all the integration.  It's all manual code at the moment (would love to create an easy-to-use API for this in the future).

> Has a good db schema for follow types (when following post types and taxonomies);

DB schema is simple enough, but you could also potentially use Posts 2 Posts:
https://github.com/scribu/wp-posts-to-posts/wiki/Posts-2-Users

One other potential problem with using BP Follow's DB schema is you have to use post IDs as the leader ID, which means that you couldn't use your proposed plugin on a WP multisite install.

Following activity items might be better.  See #67.

**Comment by renatonascalves** [comment]
Thanks @r-a-y! I'll review your suggestions! =D

**Pull request closed without merging**
